#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Academy Manager Pro - prepare the folder for hosting
====================================================

اجرا:
    python deploy_host.py

یک پوشه‌ی `host_deploy` می‌سازد که دقیقاً همان فایل‌هایی که هاست
(cPanel / Python 3.11) برای اجرای نسخه‌ی وب نیاز دارد در آن کپی شده:
بدون فایل‌های بیلد، بدون دیتابیس محلی و بدون فایل‌های حساس.
در پایان یک فایل ZIP هم می‌سازد تا راحت آپلود کنید.
"""

import ast
import json
import os
import shutil
import sys
import time
import zipfile

ROOT = os.path.dirname(os.path.abspath(__file__))
STAGE = os.path.join(ROOT, "host_deploy")

# ── فایل‌هایی که در ریشه‌ی پوشه‌ی خروجی لازم است ──
REQUIRED_FILES = [
    "app.py",
    "extensions.py",
    "config.py",
    "wsgi.py",
    "passenger_wsgi.py",
    ".htaccess",
    "VERSION",
    "requirements.txt",
    # نصب فقط-با-wheel برای هاستِ بدون کامپایلر/بدون SSH:
    # cPanel → Setup Python App → Run Pip Install روی این فایل
    "requirements-nobuild.txt",
    # مسیر VPS (Gunicorn + Nginx) — روی هاست اشتراکی لازم نیست ولی بودن ضرری ندارد
    "requirements-prod.txt",
    "gunicorn.conf.py",
    "LICENSE.txt",
    "README.md",
    "HOST_DEPLOY.md",
    # app.py این را قبل از Flask وارد می‌کند — بدون آن هاست با ModuleNotFoundError می‌خوابد
    "startup_checks.py",
    # راه‌اندازی اولیه و داده‌های پایه (first_run این دو را import می‌کند)
    "first_run.py",
    "import_rahs_data.py",
    # سامانه‌ی لایسنس
    "license_client.py",
    "license_features.py",
    "license_updater.py",
]

# NOTE: settings.json محلی عمداً کپی نمی‌شود! (رمزها/SECRET_KEY/مسیر مطلق
# ماشین توسعه را دارد و روی هاست هم دیتابیس را می‌شکند و هم نشست‌ها را.)
# به‌جایش یک settings.json تمیزِ مخصوص هاست ساخته می‌شود (HOST_SETTINGS).
OPTIONAL_FILES = []

# ── پوشه‌های کد و قالب‌ها ──
# bootstrap/ (جداسازی create_app به ماژول‌های مستقل — app.py از آن import می‌کند)
# tools/ (اسکریپت نصب هوشمند وابستگی‌ها؛ روی هاستِ بدون کامپایلر برای رفع خطای
#         «Failed building wheel for greenlet» لازم می‌شود)
DIRS = ["routes", "models", "utils", "bootstrap", "tools", "templates", "static"]

# ── پوشه‌های خالی که اپ در زمان اجرا نیاز دارد (قابل نوشتن باشند) ──
RUNTIME_DIRS = [
    "instance",
    "backups",
    "logs",
    # قرارداد Passenger برای ری‌استارت بدون پنل: touch tmp/restart.txt
    "tmp",
    os.path.join("static", "uploads"),
    os.path.join("static", "uploads", "students"),
    os.path.join("static", "uploads", "teachers"),
    os.path.join("static", "uploads", "certificates"),
    os.path.join("static", "uploads", "documents"),
]

# چیزی که هرگز نباید روی هاست برود
NEVER_COPY = {
    "__pycache__", ".git", ".venv", "venv", "env", ".idea", ".vscode",
    "build", "dist", "installer_output", "installer", "backups",
    "tests", ".pytest_cache", ".mypy_cache",
}

# ── settings.json تمیز مخصوص هاست ───────────────────────────────────
# عمداً بدون secret_key است: اولین بوت روی همان هاست کلید یکتا می‌سازد و
# ذخیره می‌کند (اگر کلید را این‌جا می‌گذاشتیم، همه‌ی هاست‌ها یک کلید
# مشترک داشتند و نشست‌ها قابل جعل بود).
HOST_SETTINGS = {
    "database": {
        "type": "sqlite",
        "sqlite_path": "instance/academy.db",
        "mysql_host": "localhost",
        "mysql_port": 3306,
        "mysql_user": "",
        "mysql_password": "",
        "mysql_database": "",
        "postgresql_host": "localhost",
        "postgresql_port": 5432,
        "postgresql_user": "",
        "postgresql_password": "",
        "postgresql_database": "",
        "pool_size": 10,
        "max_overflow": 20,
        "pool_recycle": 3600,
    },
    "server": {"host": "0.0.0.0", "port": 5000, "debug": False},
    "app": {"name": "آموزشگاه نمونه", "version": "1.0.0", "page_size": 25},
    "license": {
        "server_url": "https://ls.ariapadideh.ir",
        "channel": "stable",
        "auto_update": True,
    },
}

# ── سد دفاعی داخل پوشه‌های داده ─────────────────────────────────────
# اگر روزی Apache به‌جای Passenger مستقیم فایل سرو کرد، این‌ها جلوی خواندن
# دیتابیس/لاگ/پشتیبان و اجرای اسکریپت داخل uploads را می‌گیرند.
DENY_ALL_HTACCESS = (
    "# auto-generated by deploy_host.py — do not delete\n"
    "<IfModule mod_authz_core.c>\n"
    "    Require all denied\n"
    "</IfModule>\n"
    "<IfModule !mod_authz_core.c>\n"
    "    Order allow,deny\n"
    "    Deny from all\n"
    "</IfModule>\n"
)
UPLOADS_HTACCESS = (
    "# auto-generated by deploy_host.py — do not delete\n"
    "# فایل آپلودی فقط خوانده می‌شود؛ هیچ اسکریپتی داخل آن اجرا نشود.\n"
    "<IfModule mod_php.c>\n"
    "    php_flag engine off\n"
    "</IfModule>\n"
    "RemoveHandler .php .phtml .php3 .php4 .php5 .phps .cgi .pl\n"
    "RemoveType .php .phtml .php3 .php4 .php5 .phps .cgi .pl\n"
    "Options -ExecCGI -Indexes\n"
)


# ──────────────────────────── helpers ────────────────────────────

def _prepare_console():
    if os.name != "nt":
        return
    for stream in (sys.stdout, sys.stderr):
        try:
            if getattr(stream, "isatty", lambda: False)():
                continue
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def _default_credentials():
    """مشخصات ورود پیش‌فرض — همان مقادیر واقعی کد (بدون نیاز به Flask)."""
    try:
        sys.path.insert(0, ROOT)
        from utils.constants import (default_admin_password,
                                     default_admin_username)
        return default_admin_username(), default_admin_password()
    except Exception:
        return "admin", "admin123"
    finally:
        try:
            sys.path.remove(ROOT)
        except ValueError:
            pass


def die(msg):
    print()
    lines = str(msg).splitlines()
    print("  ✗ " + lines[0])
    for line in lines[1:]:
        print("    " + line)
    print()
    sys.exit(1)


def header():
    print()
    print("  ╔" + "═" * 58 + "╗")
    print("  ║  آماده‌سازی فایل‌ها برای آپلود روی هاست                    ║")
    print("  ║  Academy Manager Pro - آموزشگاه رهسا                       ║")
    print("  ╚" + "═" * 58 + "╝")
    print()


def step(n, total, title):
    print()
    print(f"  [{n}/{total}] {title}")
    print("  " + "─" * 58)


def dir_size_mb(path):
    total = 0
    for root, _dirs, files in os.walk(path):
        for f in files:
            fp = os.path.join(root, f)
            if os.path.isfile(fp):
                total += os.path.getsize(fp)
    return total / (1024 * 1024)


def _copy_ignore(dirpath, names):
    """حذف بایت‌کد/فایل سیستمی + آپلودهای ماشین توسعه (حریم خصوصی!)."""
    ignored = set()
    for name in names:
        if name in ("__pycache__", ".DS_Store", "Thumbs.db"):
            ignored.add(name)
        elif name.endswith((".pyc", ".pyo")):
            ignored.add(name)
    # static/uploads فقط ساختارش روی هاست لازم است، نه فایل‌هایش
    if os.path.basename(dirpath) == "static" and "uploads" in names:
        ignored.add("uploads")
    return ignored


def _repo_root_modules():
    """ماژول‌های سطح‌ریشه‌ی ریپو (foo.py → foo) — برای راستی‌آزمایی importها."""
    found = set()
    for name in os.listdir(ROOT):
        if name.endswith(".py") and os.path.isfile(os.path.join(ROOT, name)):
            found.add(name[:-3])
    return found


def _verify_staged_imports(stage):
    """آیا کدی در بسته به ماژول ریشه‌ای اشاره می‌کند که بسته‌بندی نشده؟

    قبلاً فقط importهای app.py چک می‌شد؛ حالا همه‌ی فایل‌های routes/models/
    utils/bootstrap هم اسکن می‌شوند تا روی هاست ModuleNotFoundError نگیریم.
    خروجی: فهرست مشکل‌ها (خالی = سالم).
    """
    repo_modules = _repo_root_modules()
    staged = set()
    for name in os.listdir(stage):
        if name.endswith(".py") and os.path.isfile(os.path.join(stage, name)):
            staged.add(name[:-3])
    staged_packages = {d for d in DIRS if os.path.isdir(os.path.join(stage, d))}

    problems = []
    for root, _dirs, files in os.walk(stage):
        for name in files:
            if not name.endswith(".py"):
                continue
            path = os.path.join(root, name)
            try:
                with open(path, encoding="utf-8") as handle:
                    tree = ast.parse(handle.read())
            except (OSError, SyntaxError):
                continue
            imported = set()
            for node in ast.walk(tree):
                if isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
                    imported.add(node.module.split(".")[0])
                elif isinstance(node, ast.Import):
                    for alias in node.names:
                        imported.add(alias.name.split(".")[0])
            for mod in sorted(imported):
                if mod in repo_modules and mod not in staged \
                        and mod not in staged_packages:
                    rel = os.path.relpath(path, stage).replace(os.sep, "/")
                    problems.append(f"{rel} به «{mod}.py» نیاز دارد ولی در بسته نیست")
    return problems


# ─────────────────────────────── main ────────────────────────────

def main():
    os.chdir(ROOT)
    _prepare_console()

    for f in ("app.py", "requirements.txt", "VERSION", "passenger_wsgi.py"):
        if not os.path.exists(f):
            die(
                f"فایل {f} پیدا نشد.\n"
                "  این فایل باید از پوشه‌ی اصلی پروژه اجرا شود."
            )

    version = open("VERSION", encoding="utf-8").read().strip() or "1.0.0"
    admin_user, admin_pass = _default_credentials()

    header()
    started = time.time()

    # ── [1/5] پاک‌سازی پوشه‌ی قبلی ──
    step(1, 5, "آماده‌سازی پوشه‌ی host_deploy ...")
    if os.path.exists(STAGE):
        shutil.rmtree(STAGE)
        print("      پوشه‌ی قبلی پاک شد")
    os.makedirs(STAGE)
    print("      OK")

    # ── [2/5] کپی فایل‌ها ──
    step(2, 5, "کپی فایل‌های مورد نیاز ...")
    count = 0

    # فایل‌های ریشه
    for f in REQUIRED_FILES:
        if not os.path.exists(f):
            die(f"فایل {f} در پروژه پیدا نشد — کپی متوقف شد")
        shutil.copy2(f, os.path.join(STAGE, f))
        count += 1
        print(f"      ✓ {f}")

    for f in OPTIONAL_FILES:
        if os.path.exists(f):
            shutil.copy2(f, os.path.join(STAGE, f))
            count += 1
            print(f"      ✓ {f}")

    if os.path.exists(os.path.join(ROOT, "settings.json")):
        print("      ○ settings.json محلی کپی نشد (حاوی راز/مسیر محلی است) — "
              "نسخه‌ی تمیز هاست ساخته می‌شود")

    # پوشه‌ها
    for d in DIRS:
        if not os.path.isdir(d):
            die(f"پوشه‌ی {d} در پروژه پیدا نشد — کپی متوقف شد")
        shutil.copytree(d, os.path.join(STAGE, d), ignore=_copy_ignore)
        n = sum(len(fs) for _r, _ds, fs in os.walk(os.path.join(STAGE, d)))
        count += n
        print(f"      ✓ {d}/  ({n} فایل)")

    print("      ✓ static/uploads/ انتقال نیافت (حریم خصوصی) — ساختار خالی ساخته می‌شود")

    # ── [3/5] فایل‌های مخصوص هاست ──
    step(3, 5, "ساخت settings.json و پوشه‌های runtime ...")

    for d in RUNTIME_DIRS:
        full = os.path.join(STAGE, d)
        os.makedirs(full, exist_ok=True)
        # نگه‌داشتن پوشه‌ی خالی در ZIP + جلوگیری از directory listing
        with open(os.path.join(full, ".gitkeep"), "w", encoding="utf-8") as handle:
            handle.write("")
    print("      ✓ پوشه‌های instance/ و backups/ و logs/ و زیرمجلدهای آپلود ساخته شدند")

    # سد دفاعی داخل پوشه‌های داده (در برابر سرو مستقیم توسط Apache)
    for d in ("instance", "backups", "logs"):
        with open(os.path.join(STAGE, d, ".htaccess"), "w", encoding="utf-8") as handle:
            handle.write(DENY_ALL_HTACCESS)
    with open(os.path.join(STAGE, "static", "uploads", ".htaccess"),
              "w", encoding="utf-8") as handle:
        handle.write(UPLOADS_HTACCESS)
    print("      ✓ فایل‌های محافظ .htaccess داخل پوشه‌های داده گذاشته شد")

    # settings.json تمیز مخصوص هاست (بدون هیچ رازی)
    with open(os.path.join(STAGE, "settings.json"), "w", encoding="utf-8") as handle:
        json.dump(HOST_SETTINGS, handle, indent=2, ensure_ascii=False)
    print("      ✓ settings.json تمیز هاست ساخته شد (SQLite پیش‌فرض، بدون کلید)")
    print(f"      مجموعاً {count} فایل")

    # ── [4/5] بررسی نهایی ──
    step(4, 5, "بررسی پوشه‌ی خروجی ...")
    problems = []
    for f in ("app.py", "requirements.txt", "requirements-prod.txt",
              "gunicorn.conf.py", "passenger_wsgi.py", "wsgi.py",
              ".htaccess", "settings.json"):
        if not os.path.exists(os.path.join(STAGE, f)):
            problems.append(f)
    for needed in ("startup_checks.py", "passenger_wsgi.py", "wsgi.py"):
        if not os.path.exists(os.path.join(STAGE, needed)):
            problems.append(f"{needed} (برای هاست Python 3.11 لازم است)")

    # entry point باید شیء application را صادر کند
    try:
        passenger_src = open(os.path.join(STAGE, "passenger_wsgi.py"),
                             encoding="utf-8").read()
        if "application" not in passenger_src:
            problems.append("passenger_wsgi.py شیء application را صادر نمی‌کند!")
        if "ACADEMY_DISABLE_SCHEDULER" not in passenger_src:
            problems.append("passenger_wsgi.py زمان‌بند را روی هاست اشتراکی خاموش نمی‌کند!")
    except OSError as exc:
        problems.append(f"passenger_wsgi.py خوانده نشد: {exc}")

    # ‎.htaccess نباید ریدایرکت قدیمیِ خراب‌کننده‌ی Passenger را داشته باشد
    try:
        htaccess = open(os.path.join(STAGE, ".htaccess"), encoding="utf-8").read()
        if "wsgi.py/$1" in htaccess or "wsgi.py/" in htaccess:
            problems.append(".htaccess هنوز RewriteRule خراب به wsgi.py دارد (Passenger را می‌شکند)!")
    except OSError as exc:
        problems.append(f".htaccess خوانده نشد: {exc}")

    # وابستگی‌های حیاتی باید در requirements باشند
    try:
        requirements = open(os.path.join(STAGE, "requirements.txt"),
                            encoding="utf-8").read()
        for package in ("Flask==", "Flask-SQLAlchemy", "SQLAlchemy==",
                        "Flask-Login", "PyMySQL"):
            if package not in requirements:
                problems.append(f"requirements.txt بسته‌ی {package} را ندارد!")
    except OSError as exc:
        problems.append(f"requirements.txt خوانده نشد: {exc}")

    # همه‌ی importهای محلی باید در بسته باشند (نه فقط app.py)
    problems.extend(_verify_staged_imports(STAGE))

    for banned in ("academy.db", "cookies.txt", "config.ini", "app_desktop.py",
                   "host_deploy_v", ".git"):
        if os.path.exists(os.path.join(STAGE, banned)):
            problems.append(f"{banned} (نمی‌بایست در خروجی باشد!)")
    # دیتابیس/رازِ نشت‌کرده در هر عمقی ممنوع
    for root, _dirs, files in os.walk(STAGE):
        for name in files:
            if name.endswith((".db", ".db-wal", ".db-shm", ".db-journal",
                              ".sqlite", ".sqlite3")) or name == "cookies.txt":
                problems.append(os.path.relpath(os.path.join(root, name), STAGE)
                                + " (فایل داده/راز نباید در بسته باشد!)")
    if problems:
        die("مشکلی در پوشه‌ی خروجی پیدا شد:\n  • " + "\n  • ".join(problems[:15]))
    size_mb = dir_size_mb(STAGE)
    print(f"      OK - پوشه آماده است ({size_mb:.1f} MB)")
    print("      OK - همه‌ی importهای محلی در بسته هستند")

    # ── [5/5] ساخت ZIP ──
    step(5, 5, "ساخت فایل ZIP برای آپلود ...")
    zip_name = f"host_deploy_v{version}.zip"
    zip_path = os.path.join(ROOT, zip_name)
    if os.path.exists(zip_path):
        os.remove(zip_path)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for root, dirs, files in os.walk(STAGE):
            dirs[:] = [d for d in dirs if d not in NEVER_COPY]
            # پوشه‌های خالی را هم در ZIP نگه می‌داریم
            rel = os.path.relpath(root, ROOT)
            if not files and not [d for d in dirs if d not in NEVER_COPY]:
                zf.writestr(rel.replace(os.sep, "/") + "/", "")
            for f in files:
                fp = os.path.join(root, f)
                arc = os.path.relpath(fp, ROOT).replace(os.sep, "/")
                zf.write(fp, arc)
    zmb = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"      OK: {zip_name}  ({zmb:.1f} MB)")

    # ── راهنمای آپلود ──
    total = time.time() - started
    print()
    print("  ╔" + "═" * 58 + "╗")
    print("  ║  ✅ فایل‌ها آماده‌ی آپلود هستند!                          ║")
    print("  ╚" + "═" * 58 + "╝")
    print()
    print(f"  • پوشه‌ی آماده:      {os.path.abspath(STAGE)}")
    print(f"  • فایل ZIP برای آپلود: {os.path.abspath(zip_path)}")
    print()
    print("  راهنمای آپلود (cPanel با Python 3.11):")
    print("  ─────────────────────────────────────────────────────────")
    print("  ۱. فایل ZIP را در File Manager داخل public_html آپلود و Extract کنید")
    print("     (تیک Delete archive after extraction را بزنید؛ پوشه‌ی host_deploy ساخته می‌شود)")
    print("  ۲. در cPanel وارد Setup Python App شوید و یک اپلیکیشن بسازید:")
    print("       • Python version:            3.11")
    print("       • Application root:          public_html/host_deploy")
    print("       • Application startup file:  passenger_wsgi.py")
    print("       • Application Entry point:   application")
    print("  ۳. نصب پکیج‌ها — اگر SSH/Terminal ندارید، فقط با دکمه‌ی Run Pip Install:")
    print("       • Setup Python App → اپلیکیشن → Configuration files")
    print("       • `requirements-nobuild.txt` را Add کنید (از قبل در بسته است)")
    print("       • دکمه‌ی Run Pip Install را بزنید و همین فایل را انتخاب کنید")
    print("     (این فایل `--only-binary=:all:` دارد؛ پس greenlet هرگز از سورس")
    print("     کامپایل نمی‌شود و خطای `Failed building wheel for greenlet` نمی‌دهد)")
    print("     اگر Terminal دارید، به‌جای آن می‌توانید:")
    print("       pip install --prefer-binary -r requirements.txt")
    print("     یا برای حل خودکار خطای greenlet:")
    print("       python tools/install_deps.py")
    print("  ۴. مطمئن شوید پوشه‌های instance/ و backups/ و logs/ و static/uploads/")
    print("     قابل نوشتن‌اند (در Terminal همان اپلیکیشن):")
    print("       chmod 755 instance backups logs static/uploads")
    print("  ۵. اپلیکیشن را Restart کنید و دامنه را باز کنید؛ ورود پیش‌فرض:")
    print(f"       نام کاربری: {admin_user}    رمز عبور: {admin_pass}")
    print("     ⚠ حتماً پس از اولین ورود، رمز را از بخش کاربران عوض کنید!")
    print()
    print("  نکات:")
    print("  • دیتابیس روی هاست تازه ساخته می‌شود (SQLite در instance/) —")
    print("    دیتابیس محلی شما آپلود نمی‌شود؛ settings.json هم تمیز و بدون راز است")
    print("    (SECRET_KEY در اولین بوت همان هاست ساخته و ذخیره می‌شود)")
    print("  • پشتیبان‌گیری خودکار و ربات بله روی هاست اشتراکی پیش‌فرض خاموش‌اند؛")
    print("    پشتیبان را از «مرکز پشتیبان‌گیری» داخل برنامه بگیرید")
    print("  • برای MySQL: پس از ورود، به /setup/database بروید (درایور PyMySQL")
    print("    از قبل در requirements هست) و بعد اپلیکیشن را Restart کنید")
    print("  • اگر خطای 500 دیدید: logs/passenger_error.log و logs/academy.log")
    print("    را در File Manager بخوانید — علت دقیق آن‌جاست")
    print("  • راهنمای کامل قدم‌به‌قدم در فایل HOST_DEPLOY.md داخل همین بسته است")
    print()
    print(f"  زمان کل: {int(total // 60)} دقیقه و {int(total % 60)} ثانیه")
    print()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print()
        print("  ⚠ توسط کاربر لغو شد (Ctrl+C)")
        sys.exit(1)
